### ISSUE TITLE
Different `window` objects for the contexts of @require and the UserScript

### ISSUE THREAD

**Issue by WhiteSevs** [JingMatrix/ChromeXt#106]
脚本👉[https://greasyfork.org/zh-CN/scripts/445489-%E7%BD%91%E7%9B%98%E9%93%BE%E6%8E%A5%E8%AF%86%E5%88%AB](https://greasyfork.org/zh-CN/scripts/445489-%E7%BD%91%E7%9B%98%E9%93%BE%E6%8E%A5%E8%AF%86%E5%88%AB)

当`@require`的库内进行`window`判断时，通过传递参数的`window`为被`Proxy`的window，而`@require`库内的window却是`unsafeWindow`

![{C0B6964F-5A61-4366-AB3E-55F38773560C}](https://github.com/JingMatrix/ChromeXt/assets/50544447/d9a043c8-7229-4403-b09c-3a328aa1ac1a)
![{E554E932-39B7-43fe-A00B-72178DA485EF}](https://github.com/JingMatrix/ChromeXt/assets/50544447/ec5698cb-36f4-4313-a49f-088e8ebfb6fd)

**Comment by JingMatrix** [comment]
Since you call the function `DOMUtils.width` from your own UserScript, where `unsafeWindow` is not granted, the window object is surely a proxied one.

For the context of `@require`, the `window` object is always the global one so that global definition could work.
By contrast, the `globalThis` object is proxied.

To solve the issue for your script, either you ask to grant `unsafeWindow`, or in the library `DOMUtils`, set your `window` object to be `globalThis`.

**Comment by WhiteSevs** [comment]
感谢，我使用`globalThis`代替了`window`，脚本可以正常工作了
