### ISSUE TITLE
GM_setClipboard error

### ISSUE THREAD

**Issue by WhiteSevs** [JingMatrix/ChromeXt#112]
https://github.com/JingMatrix/ChromeXt/blob/aba8e9dd1280722b71335f71475f5885e1b856c6/app/src/main/assets/GM.js#L148-L161
有些时候使用`navigator.clipboard.write`会出现`DOMException: Write permission denied.`错误导致无法写入剪贴板。
建议：对它加上`catch`，失败的话使用再进行第二种方式`document.execCommand("copy")`

**Comment by JingMatrix** [comment]
Actually, no evidence suggests that `document.execCommand("copy")` could do a better job than `navigator.clipboard.write`.
If this error is not reproducible in a definite way, then I think the best solution for the UserScipt is to catch the error and call `GM_setClipboard` again.

It would be great if you can find a way to reproduce it, so that we know what goes wrong.

**Comment by WhiteSevs** [comment]
复制`22222222`使用的是`ChromeXt`的API，未成功复制，复制`444444444`使用的是我自己的API，成功复制

https://github.com/JingMatrix/ChromeXt/assets/50544447/7eae0db8-4198-4e37-918b-679ace780d09
