### ISSUE TITLE
Adblocking

### ISSUE THREAD

**Issue by Loukious** [JingMatrix/ChromeXt#124]
> [AD Blocker solution](https://github.com/JingMatrix/ChromeXt#ad-blocker-solution)
> For blocking network requests, I recommend to use AdAway or any proxy AD Blocker such as clash.
> 
> A content cosmetic blocker is embedded into ChromeXt with the help of eruda. To use it, first open the Eruda console. In the Elements panel, one can use the pointer icon to select elements on the page. After clicking the delete icon for a selected element, a corresponding filter will be saved to the Resources panel, where one can manage previous added filters. These filters are saved in the browser even after clearing the site's data.
> 
> Another way to block ADs is using the [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src) to block some scripts from loading.

While the methods mentioned above are working, they are not perfect. Sure AdAway blocks most ads but not all of them (ads hosted on the same website domain can't be blocked) plus it leaves an ugly empty spaces for where the ads supposed to be when it works. The cosmetic blocker has a great potential, the only downside is that you have to manually add elements by yourself. If only you could make it parse the public ublock ads lists and auto add them to blocked content or maybe just provide an already parsed list yourself that the app auto sync with.

**Comment by JingMatrix** [comment]
1. I am working on supporting the `uBlock` extension and possible general extensions. However, currently I don't have too much time on it. Moreover, the implement might not be perfectly efficient.
2. Exporting cosmetic filters is an interesting feature, I may consider it in the future. Currently, the recommended solution is to write UserScripts to block ADs and sync them use other services, such as `GreasyFork`.
3. AD block using general lists found on the internet is never as efficient as using `AdAway` or system proxy, simply because `JavaScript` is not natively executed. The efficiency matters since common lists are quite huge.
4. Actually, the most visited websites in daily life are usually limited. It is not really a burden to add cosmetic filters for them manually. Personally, I combine all three methods described in the README to block ADs.
5. Some browsers has implemented AD blocking, you may try them if you are not satisfied with the above solutions.

As an example, I would like to share one of my UserScript for blocking ADs:
```javascript
// ==UserScript==
// @name	AD blocking for Baozimh 
// @namespace	JingMatrix
// @match	https://*.baozimh.com/*
// @match 	https://*manga.com/comic/chapter/*
// @grant 	GM.ChromeXt
// @grant 	unsafeWindow
// @run-at	document-start
// ==/UserScript==

const cspRule = "script-src 'self'; frame-src 'none'";
const filter = "div.div_adhost,div.mobadsq,div#interstitial_fade,div#bottom";

if (!ChromeXt.filters.includes(filter)) {
  ChromeXt.filters.push(filter);
}
if (!ChromeXt.cspRules.includes(cspRule)) {
  ChromeXt.cspRules.push(cspRule);
  window.location.reload();
}
```
I personally think that writing a specific UserScript to block ADs is more interesting, elegant and efficient than using a common AD blocking list.
Hope that my perspective may change your original opinion.
