### ISSUE TITLE
Unable to install using lspatch 

### ISSUE THREAD

**Issue by Red-Baran** [JingMatrix/ChromeXt#143]
I understand it's explained how to use this with lspatch but all I get is an error. Can you give me any additional information on how to use and install this with non-root lspatch? Sorry i don't know where else to patch this.

**Comment by JingMatrix** [comment]
Please provide enough descriptions of which apk you patch and what the error message says.
Did you follow the steps given in the video?
Most likely that you didn't pick up the lastest builds of LSPacth or ChromeXt from GitHub Actions.

**Comment by Red-Baran** [comment]
Thanks for the reply. I didn't see a video.

I used the latest builds downloaded from this github

**Comment by JingMatrix** [comment]
Here is the [link to the tutorial video on YouTube](https://www.youtube.com/watch?v=1Qm4dU-XnJM).
Please add some screenshots that show the patch fails.

**Comment by Red-Baran** [comment]
Watched the video. I wanted to patch chrome directly or chromedev. I was able to successfully patch chrome dev, however I'm not able to login to my account and worst part is it crashes

**Comment by JingMatrix** [comment]
Which Chrome Dev version you patched? And how it crashes (what trigers the crash)? If just crashes once, it is Okay (maybe due to some process in background problems).

It is normal that you are unable to login Google in Chrome after patched, it is protection enhanced by Google, see #89 

If you have root and use LSPosed, there is no problem of login.
