### ISSUE TITLE
Unable to patch brave browser using lspatch manager apk. 

### ISSUE THREAD

**Issue by Rajraimatrix** [JingMatrix/ChromeXt#168]
Tried to patch brave browser using ls patch manager apk but couldn't do it. My android phone is not rooted.

 Shizuku was activated

Bravearm64.apk

There was an error while installing the apk. 

The error says:

INSTALL_FAILED_USER_RESTRICTED: Install canceled by user

![Screenshot_2024-05-15-19-18-45-573_org lsposed lspatch](https://github.com/JingMatrix/ChromeXt/assets/169574667/a21cb6a1-804a-4b92-a3ba-0666867eb2d2)

**Comment by JingMatrix** [comment]
You should first uninstall the Brave browser, then you can install the patched APK from you file explorer.

By the way, which LSPatch version you are using?
Did you watched my YouTube tutorial video?

**Comment by Rajraimatrix** [comment]
I have watched your youtube tutorial video, In which your phone was rooted and you didn't use shizuku to patch the browser using lspatch manger apk. 

I'm using the latest lspatch manger apk that you have recently updated in github action. 

I had deleted the brave browser before the installation.

**Comment by JingMatrix** [comment]
My video also contains a part of [using LSPatch](https://youtu.be/1Qm4dU-XnJM?feature=shared&t=645).
The bug/problem you are experiencing is mostly related to Shizuku, so I suggest you to do the same as in the video:
**find your patched browser APK in the file explorer and install it manually**.

Before doing that, I suggest you to clean the data of your LSPatch app, so that you know where to put your patched browser APKs.

**Comment by Rajraimatrix** [comment]
I have did all those thing that you are saying yet I couldn't patch the browser. 

 I have made the videos of the process while patching the browser so that you can give any solution to me if I'm making any mistake while patching the browser but I couldn't upload it here since the video size is larger than 10 mb.
