### ISSUE TITLE
Why Hydrogen is not supported by ChromeXt

### ISSUE THREAD

**Issue by jinshuqishi2019** [JingMatrix/ChromeXt#173]
下面项目是一款第三方知乎客户端
https://github.com/huajiqaq/Hydrogen

现在经过我尝试，使用app打开脚本链接发现ChromeXt目前是不能使用的。

想问下，是需要ChromeXt适配才能使用；还是Hydrogen根本上就不能使用ChromeXt，谢谢。

**Comment by JingMatrix** [comment]
Why would you like to use UserScript for this app? The author delibrately disables Javascript for better user experience.

**Comment by jinshuqishi2019** [comment]
在电子书上下滑动翻页体验并不好，如果支持JS则可以利用脚本实现虚拟按钮翻页无滑动，并且支持的话可以使用翻页器。

**Comment by JingMatrix** [comment]
It is a fairly complicated app, I haven't find a solution to support it yet.
For the function you would like to have, I'd suggest to ask the author of Hydrogen for help.
I am currently unable to support it, and not motivated to do so since it requires some isolated codes to deal with this particularly non-standard ``browser''.

**Comment by jinshuqishi2019** [comment]
理解，感谢你付出的时间回答。
