### ISSUE TITLE
Support Regex matching urls

### ISSUE THREAD

**Issue by luxysiv** [JingMatrix/ChromeXt#75]
Can you support this userscript :  https://raw.githubusercontent.com/TagoDR/MangaOnlineViewer/master/dist/Manga_OnlineViewer.user.js

**Comment by JingMatrix** [comment]
The problem should be the matching urls.
You can try to change the matching urls from the front-end.
I won't change the matching algorithm of ChromeXt, otherwise it will break most of scripts other people are using.

If your script still doesn't work after changing the matching url, report it here, and I will inspect it deeper.

**Comment by JingMatrix** [comment]
Wait, I may try to support Regex matching since both Violentmonkey and Tampermonkey support it.

**Comment by JingMatrix** [comment]
Done. Thanks for reporting this issue.

**Comment by luxysiv** [comment]
Thanks for your works

**Comment by luxysiv** [comment]
ChromeXt not install script on non-root patched apk

**Comment by JingMatrix** [comment]
> ChromeXt not install script on non-root patched apk

Open new issues and describe in details your problem.

**Comment by luxysiv** [comment]
I can't install userscript above

**Comment by JingMatrix** [comment]
> I can't install userscript https://raw.githubusercontent.com/TagoDR/MangaOnlineViewer/master/dist/Manga_OnlineViewer.user.js

Cannot reproduce your problem. Describe in steps how you encounter this problem, or record your screen if that is easier for you.
