### ISSUE TITLE
Frequent crash on Edge and Vivaldi

### ISSUE THREAD

**Issue by TigerBeanst** [JingMatrix/ChromeXt#90]
Edge: Stable 115.0.1901.189(190118905)
Vivaldi: Stable 6.1.3035.258(530350258) (Chromium 114.0.5735.321)

I have tried to use CI version from GitHub Action.

![Screenshot_2023-08-06-15-25-31-834_com fankes apperrorstracking](https://github.com/JingMatrix/ChromeXt/assets/3889846/69459903-cc75-4c47-90ed-7c7b5730cbf5)
![Screenshot_2023-08-06-15-26-07-435_com fankes apperrorstracking](https://github.com/JingMatrix/ChromeXt/assets/3889846/1b4025a1-226a-4260-9777-d71ab14d7892)

[com.vivaldi.browser_2023-08-05T20_51_52.251.log](https://github.com/JingMatrix/ChromeXt/files/12268885/com.vivaldi.browser_2023-08-05T20_51_52.251.log)

**Comment by JingMatrix** [comment]
From your error log, you are not using the latest version.
Your crash is caused by some imperfect built, which misses some commits to fix the bug above.
Because the file `cosmetic_filter.js` and related codes have been removed from the latest ChromeXt.

So, could you please re-patch your browsers with the lastest [ChromeXt](https://github.com/JingMatrix/ChromeXt/actions/runs/5772436218). It might be that you patched the lastest ChromeXt but didn't install it (for example, you installed an old patched APK by accident).
Hence, check your patching processure, patch and install browsers properly.

Also, don't patch some already patched APK.
